# Generated by Django 4.1.13 on 2024-03-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airmononmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirmonOnMap',
        ),
    ]
