# Generated by Django 4.1.13 on 2024-04-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_username_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='actual_location',
        ),
    ]
