# Generated by Django 4.1.13 on 2024-04-20 11:28

import api.models.location
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_capture_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGeohash',
            fields=[
                ('geohash', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[api.models.location.GeohashValidator()])),
            ],
        ),
    ]
