# Generated by Django 4.1.13 on 2024-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_locationgeohash'),
        ('api', '0010_player_avatar_playerimages'),
    ]

    operations = [
    ]
