# Generated by Django 4.1.13 on 2024-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20240423_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airmon',
            name='image',
            field=models.ImageField(upload_to='airmons/'),
        ),
    ]
