# Generated by Django 4.2.11 on 2024-05-02 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_merge_20240425_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airmon',
            name='rarity',
            field=models.CharField(choices=[('Llegendari', 'Llegendari'), ('Epic', 'Epic'), ('Curios', 'Curios'), ('Especial', 'Especial'), ('Comu', 'Comu')], default='Comu', max_length=32),
        ),
        migrations.AlterField(
            model_name='airmon',
            name='type',
            field=models.CharField(choices=[('Lorem', 'Lorem'), ('Ipsum', 'Ipsum'), ('Dolor', 'Dolor')], default='Lorem', max_length=32),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.locationgeohash', unique=True),
        ),
    ]
