# Generated by Django 4.2.11 on 2024-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chat_friendship_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='nom_pollutant',
            field=models.CharField(default='No pollutant', max_length=32),
        ),
        migrations.AddField(
            model_name='measure',
            name='val_color',
            field=models.SmallIntegerField(default=0),
        ),
    ]
