# Generated by Django 4.2.11 on 2024-05-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chat_alter_airmon_rarity_alter_airmon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('Llegendari', 'Llegendari'), ('Epic', 'Epic'), ('Curios', 'Curios'), ('Especial', 'Especial'), ('Comu', 'Comu')], default='Comu', max_length=32),
        ),
    ]
