# Generated by Django 4.2.11 on 2024-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutant',
            name='measure_unit',
            field=models.CharField(choices=[('Micrograms/m3', 'Microgramsxmetre3'), ('Miligrams/m3', 'Miligramsxmetres3')], max_length=32),
        ),
    ]
