# Generated by Django 4.2.11 on 2024-04-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_playerimages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='playerimages',
            unique_together={('user', 'date')},
        ),
    ]
