# Generated by Django 4.2.11 on 2024-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_measure_nom_pollutant_measure_val_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='val_color',
            field=models.SmallIntegerField(default=1),
        ),
    ]
