# Generated by Django 4.2.11 on 2024-05-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chatmessage_id_alter_chatmessage_chat'),
        ('api', '0016_alter_playerimages_user_and_more'),
    ]

    operations = [
    ]
