# Generated by Django 4.2.11 on 2024-05-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_measure_val_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='val_color',
            new_name='icqa',
        ),
    ]
