# Generated by Django 4.2.11 on 2024-05-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20240502_1342'),
        ('api', '0017_rename_val_color_measure_icqa'),
    ]

    operations = [
    ]
