# Generated by Django 4.2.11 on 2024-05-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20240502_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpawnPoint',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='api.locationgeohash')),
                ('minute', models.BigIntegerField()),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='SpawnedAirmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.BigIntegerField()),
                ('airmon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airmon')),
                ('spawn_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spawnpoint')),
            ],
            options={
                'unique_together': {('spawn_point', 'airmon', 'hour')},
            },
        ),
    ]
