# Generated by Django 4.2.11 on 2024-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_pollutant_measure_unit'),
        ('api', '0019_spawnpoint_spawnedairmon'),
    ]

    operations = [
    ]
