# Generated by Django 4.2.11 on 2024-05-18 09:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_alter_friendship_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeritem',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rarity',
        ),
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/default.png', upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='playeritem',
            unique_together={('item_name', 'user')},
        ),
        migrations.CreateModel(
            name='PlayerActiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item_name', 'user')},
            },
        ),
    ]
