# Generated by Django 4.2.11 on 2024-05-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_friendship_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoryModel',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('codi', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('data_ini', models.DateTimeField()),
                ('data_fi', models.DateTimeField()),
                ('imatge', models.ImageField(upload_to='events/')),
                ('entrades', models.TextField()),
                ('espai', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventcategorymodel')),
            ],
        ),
    ]
