# Generated by Django 4.2.11 on 2024-05-21 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_trophy_playertrophy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertrophy',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='playertrophy',
            unique_together={('user', 'trophy')},
        ),
    ]
