# Generated by Django 4.2.11 on 2024-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_trophy_playertrophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='airmons_alliberats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_airmons_capturats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_consumibles_usats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='n_tirades_ruleta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_airmons_comu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_airmons_curios',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_airmons_epic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_airmons_especial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_airmons_llegendari',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_coins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_compres',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
