# Generated by Django 4.2.11 on 2024-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_eventcategorymodel_eventmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='descripcio',
            new_name='denominacio',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='entrades',
        ),
    ]
