# Generated by Django 4.2.11 on 2024-05-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_username_playeritem_user_remove_item_rarity_and_more'),
        ('api', '0023_trophy_playertrophy'),
    ]

    operations = [
    ]
