# Generated by Django 4.2.11 on 2024-05-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_descripcio_eventmodel_denominacio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='EventCategoryModel',
        ),
    ]
