# Generated by Django 4.2.11 on 2024-05-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_player_airmons_alliberats_player_n_airmons_capturats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_airmons_curios',
            new_name='total_airmons_mythical',
        ),
    ]
