# Generated by Django 4.2.11 on 2024-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20240522_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_roulette_spin',
            field=models.DateField(null=True),
        ),
    ]
