# Generated by Django 4.2.11 on 2024-05-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_trophy_description_trophy_requirement'),
        ('api', '0025_player_last_roulette_spin'),
    ]

    operations = [
    ]
