# Generated by Django 4.2.11 on 2024-05-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_total_airmons_curios_player_total_airmons_mythical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_airmons_comu',
            new_name='total_airmons_common',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='total_airmons_llegendari',
            new_name='total_airmons_legendary',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='total_airmons_especial',
            new_name='total_airmons_special',
        ),
    ]
