# Generated by Django 4.2.11 on 2024-05-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_eventmodel_category_delete_eventcategorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('codi', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('denominacio', models.TextField()),
                ('data_ini', models.DateTimeField()),
                ('data_fi', models.DateTimeField()),
                ('imatge', models.ImageField(upload_to='events/')),
                ('espai', models.TextField()),
                ('geohash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locationgeohash')),
            ],
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
    ]
