# Generated by Django 4.2.11 on 2024-05-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_event_delete_eventmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='imatge',
        ),
    ]
