# Generated by Django 4.2.11 on 2024-05-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_trophy_playertrophy'),
        ('api', '0027_remove_event_imatge'),
    ]

    operations = [
    ]
