# Generated by Django 4.2.11 on 2024-05-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_player_last_roulette_spin'),
        ('api', '0028_merge_20240523_0826'),
    ]

    operations = [
    ]
