# Generated by Django 4.2.11 on 2024-05-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20240523_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airmon',
            name='rarity',
            field=models.CharField(choices=[('LEGENDARY', 'Legendary'), ('MYTHICAL', 'Mythical'), ('EPIC', 'Epic'), ('SPECIAL', 'Special'), ('COMMON', 'Common'), ('Llegendari', 'Llegendari'), ('Curios', 'Curios'), ('Especial', 'Especial'), ('Comu', 'Comu')], default='Comu', max_length=32),
        ),
        migrations.AlterField(
            model_name='airmon',
            name='type',
            field=models.CharField(choices=[('Lorem', 'Lorem'), ('Ipsum', 'Ipsum'), ('Dolor', 'Dolor'), ('NO2', 'No2'), ('PM10', 'Pm10'), ('PM25', 'Pm25'), ('O3', 'O3'), ('SO2', 'So2'), ('CO', 'Co'), ('C6H6', 'C6H6'), ('H2S', 'H2S')], default='Lorem', max_length=32),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.locationgeohash'),
            preserve_default=False,
        ),
    ]
