# Generated by Django 4.2.11 on 2024-05-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_total_airmons_comu_player_total_airmons_common_and_more'),
        ('api', '0030_alter_airmon_rarity_alter_airmon_type_and_more'),
    ]

    operations = [
    ]
