# Generated by Django 4.2.11 on 2024-05-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20240522_2239'),
        ('api', '0031_merge_20240523_1706'),
    ]

    operations = [
    ]
