# Generated by Django 4.2.11 on 2024-05-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20240522_2236'),
        ('api', '0032_merge_20240523_2348'),
    ]

    operations = [
    ]
