# Generated by Django 4.2.11 on 2024-05-24 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0033_merge_20240523_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='pollutant',
            name='recommended_limit',
        ),
        migrations.AlterField(
            model_name='airmon',
            name='rarity',
            field=models.CharField(choices=[('LEGENDARY', 'Legendary'), ('MYTHICAL', 'Mythical'), ('EPIC', 'Epic'), ('SPECIAL', 'Special'), ('COMMON', 'Common'), ('Llegendari', 'Llegendari'), ('Curios', 'Curios'), ('Especial', 'Especial'), ('Comu', 'Comu')], default='COMMON', max_length=32),
        ),
        migrations.AlterField(
            model_name='airmon',
            name='type',
            field=models.CharField(choices=[('Lorem', 'Lorem'), ('Ipsum', 'Ipsum'), ('Dolor', 'Dolor'), ('NO2', 'No2'), ('PM10', 'Pm10'), ('PM25', 'Pm25'), ('O3', 'O3'), ('SO2', 'So2'), ('CO', 'Co'), ('C6H6', 'C6H6'), ('H2S', 'H2S')], default='NO2', max_length=32),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='type',
            field=models.CharField(choices=[('OR', 'Or'), ('PLATA', 'Plata'), ('BRONZE', 'Bronze')], default='BRONZE', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='capture',
            unique_together={('airmon', 'user', 'date')},
        ),
    ]
