# Generated by Django 4.2.11 on 2024-05-27 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_username_capture_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='attempts',
        ),
        migrations.AlterField(
            model_name='capture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='CaptureSpawnedAirmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('spawned_airmon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spawnedairmon')),
            ],
            options={
                'unique_together': {('player', 'spawned_airmon')},
            },
        ),
    ]
