# Generated by Django 4.2.11 on 2024-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_capture_attempts_alter_capture_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawnedairmon',
            name='variable_latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spawnedairmon',
            name='variable_longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
