# Generated by Django 4.2.11 on 2024-05-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_spawnedairmon_variable_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='denominacio',
        ),
    ]
