# Generated by Django 4.2.11 on 2024-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_bannedplayer'),
        ('api', '0037_remove_event_denominacio'),
    ]

    operations = [
    ]
