# Generated by Django 4.2.11 on 2024-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_0037_bannedplayer_0037_remove_event_denominacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='denominacio',
            field=models.CharField(default='', max_length=256),
        ),
    ]
