# Generated by Django 4.2.11 on 2024-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_event_denominacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airmon',
            name='rarity',
            field=models.CharField(choices=[('LEGENDARY', 'Legendary'), ('MYTHICAL', 'Mythical'), ('EPIC', 'Epic'), ('SPECIAL', 'Special'), ('COMMON', 'Common')], default='COMMON', max_length=32),
        ),
        migrations.AlterField(
            model_name='airmon',
            name='type',
            field=models.CharField(choices=[('NO2', 'No2'), ('PM10', 'Pm10'), ('PM25', 'Pm25'), ('O3', 'O3'), ('SO2', 'So2'), ('CO', 'Co'), ('C6H6', 'C6H6'), ('H2S', 'H2S')], default='NO2', max_length=32),
        ),
    ]
