# Generated by Django 4.1.13 on 2024-03-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='attemps',
            new_name='attempts',
        ),
    ]
