# Generated by Django 4.1.13 on 2024-04-16 07:20

import api.models.language
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_alter_capture_unique_together_alter_capture_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(choices=[(api.models.language.Language['CATALA'], 'Catala'), (api.models.language.Language['ANGLES'], 'Angles'), (api.models.language.Language['CASTELLA'], 'Castella')], default='Catala', max_length=16)),
                ('xp_points', models.PositiveSmallIntegerField(default=0)),
                ('coins', models.PositiveSmallIntegerField(default=0)),
                ('actual_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location')),
            ],
        ),
    ]
