# Generated by Django 4.1.13 on 2024-04-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user',
        ),
    ]
