# Generated by Django 4.1.13 on 2024-04-17 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_player_actual_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capture',
            unique_together={('airmon', 'username', 'date')},
        ),
    ]