# Generated by Django 4.1.13 on 2024-04-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20240423_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.locationgeohash'),
        ),
    ]
