# Generated by Django 4.1.13 on 2024-04-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_airmon_image'),
        ('api', '0012_alter_station_location'),
    ]

    operations = [
    ]
